import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import { cn } from "@/src/lib/utils"
import "./globals.css";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        fontSans.className,
        "h-full antialiased",
      )}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        {/* Esto crea un margen superior de 5 */}
        <main className="container mx-auto pt-5">
          {children}
        </main>
      </body>
    </html>
  );
}
